name: Commented Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@main
        if: startsWith(github.event.comment.body, '/verify')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
