name: Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  issueHandler:
    name: IssueHandler
    runs-on: windows-latest
    permissions:
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: IssueHandler
        uses: ScoopInstaller/GithubActions@main
        if: github.event.action == 'opened' || (github.event.action == 'labeled' && contains(github.event.issue.labels.*.name, 'verify'))
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
