name: Pull Requests

on:
  pull_request:
    types: [opened]

jobs:
  pullRequestHandler:
    name: PullRequestHandler
    runs-on: windows-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PullRequestHandler
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
